name: run daily_dermal_scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '15 07 * * *' # At 07:15 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install python 3.10

      - name: install Python dependencies
        run: pip install -r requirements.txt

      - name: execute dermal script # run dermal_main.py
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: python dermal_main.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 